<h2>Soal 1: Membuat Objek DataFrames</h2>

- Buatlah objek dataframes dari objek dictionary, Bebas!

In [92]:
# Membuat dataframes dari dictionary
import pandas as pd

df = pd.DataFrame({'Nomor Identitas': [12, 34, 56], 'Nama': ['Jabbar', 'Abdul', 'Hafizh']})
print(display(df))

# check tipe data
print(type(df))

   Nomor Identitas    Nama
0               12  Jabbar
1               34   Abdul
2               56  Hafizh

None
<class 'pandas.core.frame.DataFrame'>

<h2>Soal 2: Membaca data dari file</h2>

Download file bernama [diamonds.csv](https://drive.google.com/uc?export=download&id=1qQiM9utQUThTPq8jk8stPMh_y2zfqYOd), kemudian baca data tersebut dan assign ke dalam suatu variabel kemudian print.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [3]:
path = "/content/drive/My Drive/Colab Notebooks/Tugas Hari 1 Pekan 2 - Abdul Jabbar Hafizh/diamonds-1.csv"
df_diamonds = pd.read_csv(path)

df_diamonds

       Unnamed: 0  carat        cut color  ... price     x     y     z
0               1   0.23      Ideal     E  ...   326  3.95  3.98  2.43
1               2   0.21    Premium     E  ...   326  3.89  3.84  2.31
2               3   0.23       Good     E  ...   327  4.05  4.07  2.31
3               4   0.29    Premium     I  ...   334  4.20  4.23  2.63
4               5   0.31       Good     J  ...   335  4.34  4.35  2.75
...           ...    ...        ...   ...  ...   ...   ...   ...   ...
53935       53936   0.72      Ideal     D  ...  2757  5.75  5.76  3.50
53936       53937   0.72       Good     D  ...  2757  5.69  5.75  3.61
53937       53938   0.70  Very Good     D  ...  2757  5.66  5.68  3.56
53938       53939   0.86    Premium     H  ...  2757  6.15  6.12  3.74
53939       53940   0.75      Ideal     D  ...  2757  5.83  5.87  3.64

[53940 rows x 11 columns]

Expected Result:

![alt text](https://drive.google.com/uc?id=1BvgM5mJEVfj0fllrjkBfQwn0QIFkry_t)

<h2>Soal 3: DataFrame vs Series</h2>

- Apa perbedaan Series dengan list dan dictionary
> Series List
- index seriesnya tidak harus bertipe int
- Ketika print obj_series akan menampilkan index dan value nya.
- Ketika print list akan menampilkan value nya saja.
> Series Dict
- Dapat mempunyai duplicate key yang sama
- Bisa slicing

- Apa perbedaan dataframe dan series

> Perbedaan dari Series dan DataFrame ini terletak pada strukturnya dan juga attribute dan method-method yang mereka miliki, untuk perbedaan strukturnya adalah sebagai berikut :


*   > Series adalah objek 1 dimensi. Series adalah suatu objek satu dimensi yang dapat menyimpan berbagai jenis tipe data seperti integer, string, dan lain sebagainya. tipe data dari objek series ini harus seragam.

*   > DataFrame adalah suatu objek 2 dimensi, mirip seperti tabel. DataFrame adalah suatu objek 2 dimensi tempat menyimpan data dengan lebih terstruktur. dataframe memiliki 2 index, yaitu index baris dan index columns. Dalam satu column dataframe harus memiliki tipe data yang sama. tapi antar columnnya dataframe bisa memiliki jenis data yang berbeda.




- Buatlah suatu data series

Jawab:

In [4]:
# code here
# cara pertama
x = pd.Series([6,3,4,6])
print(x)

x.index = ['a', 'b', 'c', 'd']
print(x)

# cara kedua
x = pd.Series([6,3,4,6], index=['a', 'b', 'c', 'd'])
print(x)
print(type(x))

0    6
1    3
2    4
3    6
dtype: int64
a    6
b    3
c    4
d    6
dtype: int64
a    6
b    3
c    4
d    6
dtype: int64
<class 'pandas.core.series.Series'>

<h2>Soal 4: Pemeriksaan Data Sederhana</h2>

Di soal no 2 kamu telah membaca data tentang diamonds. pada soal ini cobalah suatu metode dari pandas untuk mengetahui beberapa data pertama dan beberapa data terakhir. kemudian sebutkan nilai dari:
- baris pertama dari column price
- baris terakhir dari column color

tunjukan cara kalian menemukan nilai tersebut di block di bawah ini.

In [5]:
# code here
end_column = len(df_diamonds)-1
print(df_diamonds['price'][0])
print(df_diamonds['color'][end_column])

326
D

<h2>Soal 5: Deskriptif Statistik</h2>

Jelaskan apa itu deskriptis statistik!

Jawab: 
> Statistika deskriptif merupakan suatu metode yang berhubungan dengan pengumpulan atau penyajian data sampai memberi informasi yang berguna.

Statistika di golongkan menjadi dua bagian, yakni statistika deskriptif dan statistika inferensia yang dilakukan berdasarkan aktivitas yang dilakukan.

Untuk contoh dari statistika deskriptif sendiri antara lain yaitu:

- tabel
- diagram
- grafik
- besaran-besaran lain dalam majalah dan koran-koran.

> Statistika deskriptif berkaitan dengan bagaimana kita
menjelaskan dan murumuskan suatu data. Umumnya digunakan dua metode pendekatan:

- Pendekatan kuantitatif menjelaskan data secara
numerik.
- Pendekatan visual mengilustrasikan data
menggunakan chart, plot, histogram, atau grafik lainnya.
Kita dapat menerapkan statistika deskriptif ke dalam satu atau banyak data. Ketika kita menjelaskan dan merumuskan suatu data tunggal, maka kita sedang melakukan analisa univariate. Ketika kita mencari hubungan statistika antara sepasang data, maka kita sedang melakukan analisa bivariate. Begitu juga dengan analisa multivariate yang berarti kita menerapkannya pada banyak data sekaligus.

<h2>Soal 6: Practice Deskriptif Statistik</h2>

- Gunakan suatu metode dari pandas untuk mengetahui deskriptif statistik dari suatu data
- Berapa nilai rata-rata dari column price
- Berapa nilai standar deviasi dari column depth
- Berapa nilai maximum dari column carat

In [6]:
# code here
# menentukan dataframe
c_price = df_diamonds['price']
c_depth = df_diamonds['depth']
c_carat = df_diamonds['carat']

# rata-rata column price
print(f'Rata-rata Column Price: {c_price.mean()}\n')

# standar deviasi column depth
print(f'Standar Deviasi Column Depth: {c_depth.std()}\n')

# max dan min column carat
print('Max dan Min dari Carat\n''Max: ',c_carat.max(),'\nMin: ',c_carat.min())

Rata-rata Column Price: 3932.799721913237

Standar Deviasi Column Depth: 1.4326213188337733

Max dan Min dari Carat
Max:  5.01
Min:  0.2